In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

In [3]:
def mae(y_true, y_predicted):
    total_error = 0 
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total error:", total_error)
    
    mae = total_error / len(y_true)
    print("MAE:", mae)
    return mae

In [4]:
mae(y_true, y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [6]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [13]:
np.log([0.000000000000000001])

array([-41.44653167])

In [14]:
epsilon = 1e-15

In [20]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [21]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [22]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [23]:
np.log(y_predicted)

C:\Users\ASUS\AppData\Local\Temp/ipykernel_10244/815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [24]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [27]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [28]:
log_loss(y_true, y_predicted)

17.2696280766844

## Exercise

Implement mean squared error (or MSE) in two ways:

1) Without using numpy (i. e., using plain python)

2) With the use of numpy

In [29]:
import numpy as np

In [30]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

In [31]:
def mse(y_true, y_predicted):
    total_error = 0 
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt - yp)**2
    print("Total error:", total_error)
    
    mae = total_error / len(y_true)
    print("MSE:", mae)
    return mae

In [36]:
mse(y_true, y_predicted)

Total error: 1.83
MSE: 0.366


0.366

In [37]:
np.mean((y_predicted - y_true)**2)

0.366